trigger:
- master
- new/*

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  GitVersion.SemVer: ''

steps:

- task: gitversion/setup@0
  inputs:
    versionSpec: '5.x'

- task: gitversion/execute@0

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '-p:Version=$(GitVersion.SemVer) -c Release'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    nobuild: true
    arguments: '-c Release'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)'
    artifact: 'source'
    publishLocation: 'pipeline'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/zxcvbn-core.csproj'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'GitVersion.FullSemVer'
    includeSymbols: true

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'drop'
    publishLocation: 'pipeline'
